---
jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: maven-resource
      trigger: true
    - get: version
      params: {pre: rc}
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-rc
    params:
      build: maven-resource
      tag: version/version
      tag_as_latest: false

- name: test
  public: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: project
      resource: maven-resource
      passed: [build]
    - get: maven-resource-image-rc
      trigger: true
      passed: [build]
    - get: version
      passed: [build]
  - task: test
    image: maven-resource-image-rc
    config:
      platform: linux
      params:
        MVN_REPO_URL: {{repo-url}}
        MVN_SNAPSHOT_URL: {{repo-snapshot-url}}
        MVN_USERNAME: ((mvn.username))
        MVN_PASSWORD: ((mvn.password))
        MVN_SKIP_CERT_CHECK: {{repo-skip-cert-check}}
        MVN_REPO_CERT: {{repo-cert}}
        MVN_DISABLE_REDEPLOY: {{repo-disable-redeploy}}
      run:
        path: sh
        args:
        - -exc
        - |
          /opt/resource/itest/all.sh

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - in_parallel:
    - get: project
      resource: maven-resource
      passed: [test]
    - get: maven-resource-image-rc
      passed: [test]
      params: {save: true}
    - get: version
      passed: [test]
      params: {bump: final}
    - get: pipeline-tasks
  - task: generate-github-release
    file: pipeline-tasks/generate-github-release/task.yml
    output_mapping: {task-output: generate-github-release-output}
  - task: generate-commitish
    file: pipeline-tasks/generate-commitish/task.yml
    output_mapping: {task-output: generate-commitish-output}
  - task: generate-release-notes
    file: pipeline-tasks/generate-release-notes-from-changelog/task.yml
    input_mapping: {task-input: project}
    output_mapping: {task-output: generate-release-notes-output}
  - put: github-release
    params:
      name: generate-github-release-output/release-name
      tag: generate-github-release-output/release-tag
      commitish: generate-commitish-output/commitish
      body: generate-release-notes-output/RELEASE_NOTES.md
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-final
    params:
      load: maven-resource-image-rc
      tag: version/version
      tag_as_latest: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

resources:
- name: maven-resource
  type: git
  source:
    uri: {{git-uri}}
    branch: {{git-branch}}
    private_key: ((git_key.private_key))
    ignore_paths:
    - LICENSE
    - NOTICE.md
    - pipeline.yml
    - README.md

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{git-uri-semver}}
    branch: version
    file: version
    private_key: ((git_key.private_key))

- name: maven-resource-image-rc
  type: docker-image
  source:
    repository: {{docker-repository-rc}}
    username: ((docker.username))
    password: ((docker.password))

- name: maven-resource-image-final
  type: docker-image
  source:
    repository: {{docker-repository-final}}
    username: ((docker.username))
    password: ((docker.password))

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-uri}}
    branch: {{pipeline-tasks-git-branch}}

- name: github-release
  type: github-release
  source:
    owner: {{github-release-user}}
    repository: maven-resource
    access_token: ((github_access_token))
