---
jobs:
- name: build
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: project
      resource: maven-resource
      trigger: true
    - get: version
      params: {pre: rc}
  - task: generate-docker-tags
    file: project/ci/generate-docker-tags.yml
    output_mapping: {task-output: generate-docker-tags-output}
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-rc-debian
    params:
      build: project
      dockerfile: project/debian/Dockerfile
      tag: generate-docker-tags-output/tag-debian
      tag_as_latest: false
  - put: maven-resource-image-rc-alpine
    params:
      build: project
      dockerfile: project/Dockerfile
      tag: generate-docker-tags-output/tag-alpine
      tag_as_latest: false
  - put: tracker
    params:
      repos:
        - maven-resource

- name: shipit
  public: true
  serial_groups: [version]
  plan:
  - aggregate:
    - get: pipeline-tasks
    - get: project
      resource: maven-resource
      passed: [build]
    - get: maven-resource-image-rc-alpine
      passed: [build]
      params: {save: true}
    - get: maven-resource-image-rc-debian
      passed: [build]
      params: {save: true}
    - get: version
      passed: [build]
      params: {bump: final}
  - task: generate-docker-tags
    file: project/ci/generate-docker-tags.yml
    output_mapping: {task-output: generate-docker-tags-output}
  - task: generate-github-release
    file: pipeline-tasks/generate-github-release/task.yml
    output_mapping: {task-output: generate-github-release-output}
  - task: generate-commitish
    file: pipeline-tasks/generate-commitish/task.yml
    output_mapping: {task-output: generate-commitish-output}
  - task: generate-release-notes
    file: pipeline-tasks/generate-release-notes-from-changelog/task.yml
    input_mapping: {task-input: project}
    output_mapping: {task-output: generate-release-notes-output}
  - put: github-release
    params:
      name: generate-github-release-output/release-name
      tag: generate-github-release-output/release-tag
      commitish: generate-commitish-output/commitish
      body: generate-release-notes-output/RELEASE_NOTES.md
  - put: version
    params: {file: version/version}
  - put: maven-resource-image-final-debian
    params:
      load: maven-resource-image-rc-debian
      dockerfile: maven-resource/debian/Dockerfile
      tag: generate-docker-tags-output/tag-debian
      tag_as_latest: false
  - put: maven-resource-image-final-alpine
    params:
      load: maven-resource-image-rc-alpine
      dockerfile: maven-resource/Dockerfile
      tag: generate-docker-tags-output/tag-alpine
      tag_as_latest: true

- name: major
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: major, pre: rc}
  - put: version
    params: {file: version/version}

- name: minor
  public: true
  serial_groups: [version]
  plan:
  - get: version
    params: {bump: minor, pre: rc}
  - put: version
    params: {file: version/version}

- name: patch
  public: true
  serial_groups: [version]
  plan:
  - get: version
    passed: [shipit]
    params: {bump: patch, pre: rc}
    trigger: true
  - put: version
    params: {file: version/version}

resources:
- name: maven-resource
  type: git
  source:
    uri: {{maven-resource-git-uri}}
    branch: {{maven-resource-git-branch}}
    private_key: {{git-private-key}}
    ignore_paths:
    - LICENSE
    - NOTICE.md
    - pipeline.yml
    - README.md

- name: github-release
  type: github-release
  source:
    access_token: {{github-release-access-token}}
    repository: maven-resource
    user: {{github-release-user}}

- name: pipeline-tasks
  type: git
  source:
    uri: {{pipeline-tasks-git-uri}}
    branch: {{pipeline-tasks-git-branch}}

- name: version
  type: semver
  source:
    driver: git
    initial_version: 1.0.0-rc.0
    uri: {{maven-resource-semver-git-uri}}
    branch: {{maven-resource-semver-git-branch}}
    file: version
    private_key: {{git-private-key}}

- name: maven-resource-image-rc-alpine
  type: docker-image
  source:
    repository: {{docker-repository-rc}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: maven-resource-image-rc-debian
  type: docker-image
  source:
    repository: {{docker-repository-rc}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: maven-resource-image-final-alpine
  type: docker-image
  source:
    repository: {{docker-repository-final}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: maven-resource-image-final-debian
  type: docker-image
  source:
    repository: {{docker-repository-final}}
    username: {{docker-username}}
    password: {{docker-password}}

- name: tracker
  type: tracker
  source:
    token: {{tracker-api-token}}
    project_id: {{tracker-project-id}}
    tracker_url: {{tracker-url}}
