#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)

cat > $payload <&0

url=$(jq -r '.source.url // ""' < $payload)
artifact=$(jq -r '.source.artifact // ""' < $payload)
version=$(jq -r '.version.version // ""' < $payload)

# groupId:artifactId:type[:classifier]
groupId=$(get_group_id $artifact)
artifactId=$(get_artifact_id $artifact)

metadataUrl="$url/${groupId//.//}/$artifactId/maven-metadata.xml"

pattern=$([ -z "$version" ] && echo "\$p" || echo "/^$version\$/,\$p")

curl $metadataUrl \
  | xmllint --xpath "/metadata/versioning/versions/version" - \
  | awk -F'</?version>' '{for(i=2;i<=NF;i++) if ($i != "") print $i}' \
  | sed -n "${pattern}" \
  | sed 's/.*/{ "version": "&" }/' \
  | jq --slurp .
